name: Actualizar Plano Aguas Vivas

on:
  repository_dispatch: 
    types: [webhook_update_aguas_vivas] # Trigger específico para Make.com
  schedule:
    - cron: '30 * * * *' # Se ejecuta al minuto 30 de cada hora (para no chocar con el otro)
  workflow_dispatch:      # Permite el botón de "Run workflow" manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar librerías
      run: |
        pip install -r requirements.txt

    - name: Ejecutar script de generación
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
      run: python plano_aguas_vivas.py

    - name: Preparar carpeta pública
      run: |
        mkdir -p public
        # Copiamos archivos base
        cp index.html public/index.html || echo "No hay index.html"
        cp Obras.html public/Obras.html || echo "No hay Obras.html"
        
        # Copiamos assets visuales
        cp logo.png public/logo.png || echo "No se encontró logo.png"
        cp fondo.png public/fondo.png || echo "No se encontró fondo.png"
        cp loguito.png public/loguito.png || echo "No se encontró loguito.png"
        cp Plano Aguas Vivas.png public/Plano Aguas Vivas.png || echo "No se generó Plano Aguas Vivas.png"
        
        
        # RESULTADOS PLANOS
        cp plano_aguas_vivas.html public/plano_aguas_vivas.html || echo "No se generó plano_aguas_vivas.html"
        cp obra_campos_del_sur_ii.html public/obra_campos_del_sur_ii.html || echo "No se generó el plano de la obra campos del sur II"

    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
