name: Actualizar Plano Obra

on:
  repository_dispatch: 
    types: [webhook_update]
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch:      # Permite ejecución manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar librerías
      run: |
        pip install -r requirements.txt

    - name: Ejecutar script de generación
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
      run: python plano_obra_campos_del_sur_ii.py

    - name: Preparar carpeta pública
      run: |
        mkdir -p public
        # Copiamos los archivos base de la web
        cp index.html public/index.html
        cp Obras.html public/Obras.html || echo "No hay Obras.html"
        cp espera.html public/espera.html || echo "No hay espera.html"
        cp actualizar.html public/actualizar.html || echo "No hay actualizar.html"
        
        # COPIAR LOGO Y FONDO (Para que no desaparezcan)
        cp logo.png public/logo.png || echo "No se encontró logo.png"
        cp fondo.png public/fondo.png || echo "No se encontró fondo.png"
        cp loguito.png public/loguito.png || echo "No se encontró loguito.png"
        cp Plano Aguas Vivas.png public/Plano Aguas Vivas.png || echo "No se generó Plano Aguas Vivas.png"
        cp plano2.png public/plano2.png || echo "No hay plano.png"
        
        # RESULTADOS PLANOS
        cp obra_campos_del_sur_ii.html public/obra_campos_del_sur_ii.html || echo "No se generó el plano de la obra campos del sur II"
        cp plano_aguas_vivas.html public/plano_aguas_vivas.html || echo "No se generó plano_aguas_vivas.html"

    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        # Con peaceiris, 'keep_files: false' es seguro aquí porque 
        # estamos reconstruyendo la carpeta 'public' completa cada vez.
